# Generated by Django 4.2.6 on 2023-11-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permiso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'permissions': (('list_permiso', 'Puede listar permisos'), ('listar_permiso2', 'Puede listar permisos'))},
        ),
    ]
