# Generated by Django 4.2.6 on 2023-11-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_permiso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'permissions': (('list_permiso', 'Puede listar permisos'), ('view_nestado', 'Puede listar los estados en la db de enrrolamiento'), ('add_nestado', 'Puede adicoinar estados en la db de enrrolamiento'), ('change_nestado', 'Puede actualizar estados en la db de enrrolamiento'), ('delete_nestado', 'Puede eliminar estados en la db de enrrolamiento'))},
        ),
    ]
