# Generated by Django 4.2.6 on 2023-11-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_permiso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'permissions': (('list_permiso', 'Puede listar permisos'), ('view_nestado', 'Puede listar estados en la db de enrrolamiento'), ('add_nestado', 'Puede adicoinar estados en la db de enrrolamiento'), ('change_nestado', 'Puede actualizar estados en la db de enrrolamiento'), ('delete_nestado', 'Puede eliminar estados en la db de enrrolamiento'), ('view_dciudadano', 'Puede listar ciudadanos en la db de enrrolamiento'), ('add_dciudadano', 'Puede adicoinar ciudadanos en la db de enrrolamiento'), ('change_dciudadano', 'Puede actualizar ciudadanos en la db de enrrolamiento'), ('delete_dciudadano', 'Puede eliminar ciudadanos en la db de enrrolamiento'), ('view_dciudadanobash', 'Puede listar ciudadanos bash en la db de enrrolamiento'), ('add_dciudadanobash', 'Puede adicoinar ciudadanos bash en la db de enrrolamiento'), ('change_dciudadanobash', 'Puede actualizar ciudadanos bash en la db de enrrolamiento'), ('delete_dciudadanobash', 'Puede eliminar ciudadanos bash en la db de enrrolamiento'), ('view_dimagenfacial', 'Puede listar imagen facial en la db de enrrolamiento'), ('add_dimagenfacial', 'Puede adicoinar imagen facial en la db de enrrolamiento'), ('change_dimagenfacial', 'Puede actualizar imagen facial en la db de enrrolamiento'), ('delete_dimagenfacial', 'Puede eliminar imagen facial en la db de enrrolamiento'))},
        ),
    ]
